# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SubscriptBea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SubscriptBea

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'IQKeyboardManagerSwift'
end
